language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vipul2605/docker_project -f Dockerfile.dev .

script:
  - docker run -e CI=true vipul2605/docker_project npm run test